// // fakeProducts.js
// export const products = [
//   {
//     id: 1,
//     name: 'Men Shirt',
//     category: 'Fashion',
//     subcategory: 'Men',
//     price: 50,
//     rating: 4,
//     image: '/image/product1.jpg',
//   },
//   {
//     id: 2,
//     name: 'Women Dress',
//     category: 'Fashion',
//     subcategory: 'Women',
//     price: 70,
//     rating: 5,
//     image: '/image/product2.jpg',
//   },
//   {
//     id: 3,
//     name: 'Kids T-shirt',
//     category: 'Fashion',
//     subcategory: 'Kids',
//     price: 30,
//     rating: 3,
//     image: '/image/product3.jpg',
//   },
//   {
//     id: 4,
//     name: 'Laptop XYZ',
//     category: 'Electronics',
//     subcategory: 'Laptops',
//     price: 500,
//     rating: 4,
//     image: '/image/product4.jpg',
//   },
//   {
//     id: 5,
//     name: 'Smart Watch',
//     category: 'Electronics',
//     subcategory: 'Smart Watch Accessories',
//     price: 120,
//     rating: 5,
//     image: '/image/product5.jpg',
//   },
//   {
//     id: 6,
//     name: 'Men Bag',
//     category: 'Bags',
//     subcategory: 'Men Bags',
//     price: 80,
//     rating: 4,
//     image: '/image/product6.jpg',
//   },
//   {
//     id: 7,
//     name: 'Women Bag',
//     category: 'Bags',
//     subcategory: 'Women Bags',
//     price: 90,
//     rating: 5,
//     image: '/image/product7.jpg',
//   },
//   {
//     id: 8,
//     name: 'Men Shoes',
//     category: 'Footwear',
//     subcategory: 'Men Footwear',
//     price: 60,
//     rating: 4,
//     image: '/image/product8.jpg',
//   },
//   {
//     id: 9,
//     name: 'Women Heels',
//     category: 'Footwear',
//     subcategory: 'Women Footwear',
//     price: 75,
//     rating: 5,
//     image: '/image/product9.jpg',
//   },
//   // Add more products for all categories and subcategories
// ];
